#!/bin/sh
_cut=`which cut`
: ${_cut:?}
_grep=`which grep`
: ${_grep:?}
_more=`which more`
_svn=`which svnlite`
: ${_svn:?}
_printf=`which printf`
: ${_printf:?}
_id=`which id`
: ${_id:?}
_src=/usr/src

# it assumed that only root can write updates to your
# system sources
if [ `$_id -u` -ne 0 ]; then
  $_printf '%s\n' 'root permission required' >&2
  exit 77
fi

#
if [ ! -d $_src ]; then
  $_printf '%s\n' "$_src is not a directory" >&2
  exit 65
fi

#
if ! $_svn info $_src >/dev/null 2>&1; then
  $_printf '%s\n' "$_src is not a svn working copy" >&2
  exit 65
fi

# get svn revision of current checkout
_rev_A=`$_svn info $_src | $_grep ^Revision | $_cut -d' ' -f 2`
: ${_rev_A:?}

# update source
$_svn up $_src

# get svn revision after source update
_rev_B=`$_svn info $_src | $_grep ^Revision | $_cut -d' ' -f 2`
: ${_rev_B:?}

# show the commit log if changes were pulled
if [ $_rev_A -ne $_rev_B ]; then
  _rev_LOGSTART=$(( _rev_A + 1 ))
  $_svn log -r ${_rev_LOGSTART}:${_rev_B} $_src | ${PAGER:-${_more:?}}
fi
